### ISSUE TITLE
Initialize gacha card schema 

### ISSUE THREAD

**Issue by austinpray** [austinpray/kaori#21]
Current schema as of https://github.com/austinpray/kaori/tree/2ccc04e32554bce258d44a65b3a5781478ede57f/kaori/plugins/gacha/models

![cards1](https://user-images.githubusercontent.com/2192970/80807864-dcd2ca80-8b83-11ea-940c-0a48d19d994c.png)

**Comment by DarrenCattle** [comment]
??? ???

**Comment by MattrMorg** [comment]
?????????

**Comment by DarrenCattle** [comment]
Name
Type
HP
Rarity
Level
Value

**Comment by MattrMorg** [comment]
![image](https://user-images.githubusercontent.com/56664515/79821562-b6778880-8354-11ea-9e13-e85caf1fa6a8.png)

**Comment by austinpray** [comment]
Current schema as of https://github.com/austinpray/kaori/tree/2ccc04e32554bce258d44a65b3a5781478ede57f/kaori/plugins/gacha/models

![cards1](https://user-images.githubusercontent.com/2192970/80807864-dcd2ca80-8b83-11ea-940c-0a48d19d994c.png)

**Comment by austinpray** [comment]
Current schema as of https://github.com/austinpray/kaori/tree/2ccc04e32554bce258d44a65b3a5781478ede57f/kaori/plugins/gacha/models

![cards1](https://user-images.githubusercontent.com/2192970/80807864-dcd2ca80-8b83-11ea-940c-0a48d19d994c.png)
