### ISSUE TITLE
cannot reference gacha engine Card class in production code

### ISSUE THREAD

**Issue by austinpray** [austinpray/kaori#67]
We correctly set mdv and rich as dev dependencies 

https://github.com/austinpray/kaori/blob/5ccdbf7f95ee8d9bbd1f8fc9556cc60ad1c06708/pyproject.toml#L29-L30

But then we reference rich in the core Card class:

https://github.com/austinpray/kaori/blob/5ccdbf7f95ee8d9bbd1f8fc9556cc60ad1c06708/kaori/plugins/gacha/engine/core/card.py#L8

This means that you will be unable to do

```python
from kaori.plugins.gacha.engine.core import Card
```

you get

```
>>> from kaori.plugins.gacha.engine.core import Card
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/app/kaori/plugins/gacha/engine/__init__.py", line 3, in <module>
    from .core import *
  File "/app/kaori/plugins/gacha/engine/core/__init__.py", line 3, in <module>
    from .card import Card
  File "/app/kaori/plugins/gacha/engine/core/card.py", line 8, in <module>
    from rich.table import Table
ModuleNotFoundError: No module named 'rich'
```

## action

- [ ] move all card rendering concerns out of the Card class itself. All things card rendering (markdown or otherwise) should live in https://github.com/austinpray/kaori/tree/master/kaori/plugins/gacha/engine/test

**Comment by ridhoq** [comment]
Bleh. Is this blocking you?

**Comment by austinpray** [comment]
@ridhoq not strictly:

![image](https://user-images.githubusercontent.com/2192970/83440249-3ab83380-a40a-11ea-96f9-5b13f2280a72.png)

But this breaks the pretty output until this issue is closed
